# Generated by Django 2.2.2 on 2019-07-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
