# Generated by Django 2.2.2 on 2019-07-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190701_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='item',
            field=models.TextField(help_text='Введите текст', max_length=10000),
        ),
    ]
